default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sport_development

test:
  <<: *default
  database: sport_test

cucumber:
  <<: *default
  database: sport_test

production:
  <<: *default
  database: sport_production
  username: xam
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>